name = "nuxt-cloudflare-multi-tenancy"
compatibility_date = "2025-01-07"
compatibility_flags = ["nodejs_compat"]

main = "./.output/server/index.mjs"
assets = { directory = "./.output/public/", binding = "ASSETS" }

# change this to your domain
routes = [{ pattern = "*.my-company.com/*", zone_name = "my-company.com" }]

# other options...
